// Horse Tinder — profile data. Photos live in img/horses (see CREDITS.md).
const P = (k, n, cap) => ({ src: `img/horses/${k}-${n}.jpg`, cap });

const HORSES = [
  { id: 'thunder', name: 'Thunder', age: 6, breed: 'Arabian', sex: 'Stallion', loc: 'Dubai, UAE', height: "6'0 (on hind legs)",
    photos: [P('thunder', 1, 'desert era'), P('thunder', 2, 'me at my trot')],
    bio: "6'0 if I stand on my hind legs. Professional carrot enthusiast. Don't swipe right if you can't handle me at my trot.",
    traits: ['Competitive', 'Loyal', 'Slightly insane'], looking: 'Someone who can keep up 🏁',
    stats: { 'Top speed': '64 km/h', 'Carrots eaten': '14,203' }, flags: ['Has kicked 3 stable doors.'], chance: 0.55,
    lines: ["i just did 3 laps of the desert for no reason", "u ever gallop so hard u see god", "i'm not competitive. i'm just better", "race u to the water trough. go", "that door had it coming"] },
  { id: 'buttercup', name: 'Buttercup', age: 8, breed: 'Palomino Quarter Horse', sex: 'Mare', loc: 'Nashville, TN', height: '15.1 hands',
    photos: [P('buttercup', 1), P('buttercup', 2, 'golden hour, golden horse'), P('buttercup', 3)],
    bio: "Sweet as a sugar cube, twice as crunchy. Country music, long trail rides, and crying at barn dances. Hay y'all 🌻",
    traits: ['Sweet', 'Southern', 'Crier'], looking: 'A cowboy. Or the horse of a cowboy.',
    stats: { 'Sugar cubes': '9,001', 'Neigh rating': '★★★★★' }, flags: ['Knows every line dance. Will make you do them.'], chance: 0.6,
    lines: ["hay y'all 🌻", "bless your heart", "wanna go line dancing? i lead", "my mama always said never trust a horse without a barn", "aw shucks 🥺"] },
  { id: 'greg', name: 'Greg', age: 11, breed: 'Bay Warmblood', sex: 'Gelding', loc: 'Swindon, UK', height: '16.2 hands',
    photos: [P('greg', 1, 'me at my fence'), P('greg', 2, 'me at my fence (again)'), P('greg', 3, 'fence')],
    bio: "Just Greg. I like fields. I have a fence I lean on. That's about it really.",
    traits: ['Normal', 'Punctual', 'Fence-based'], looking: 'Someone to stand next to.',
    stats: { 'Fences leaned on': '1', 'Excitement': 'moderate' }, flags: ['All his photos are the same fence.'], chance: 0.75,
    lines: ["hello", "how was ur day", "i stood in the field today. was good", "the fence is doing well thanks for asking", "lovely weather for standing"] },
  { id: 'horsey', name: 'Horsey McHorseface', age: 5, breed: 'Internet Poll Result', sex: 'Gelding', loc: 'The Internet', height: '15 hands + 1 meme',
    photos: [P('horsey', 1, 'blep'), P('horsey', 2, 'me when the hay arrives'), P('horsey', 3, 'vibing')],
    bio: "Named by 124,000 strangers online. None of them asked me. Tongue out 90% of the time. The other 10% I'm asleep.",
    traits: ['Chaotic', 'Viral', 'Blep'], looking: 'Clout. And you.',
    stats: { 'Bleps per day': '312', 'Neigh rating': '★★☆☆☆' }, flags: ['Communicates exclusively in memes.'], chance: 0.6,
    lines: ["blep", "this is so sad alexa play old town road", "no thoughts just hay", "me: 🐴 you: 🤨", "it's giving... horse"] },
  { id: 'pablo', name: 'Pablo', age: 9, breed: 'Appaloosa', sex: 'Stallion', loc: 'Barcelona, Spain', height: '15.3 hands',
    photos: [P('pablo', 1, 'my entourage'), P('pablo', 2, 'the canvas is me'), P('pablo', 3)],
    bio: 'Artist. Spotted, not stirred. The birds follow me because they recognise genius. My spots are a limited edition.',
    traits: ['Artsy', 'Pretentious', 'Spotted'], looking: 'A muse. Must stand very still.',
    stats: { 'Birds following': '4', 'Paintings sold': '0' }, flags: ['Calls his spots "a statement".'], chance: 0.5,
    lines: ["art is just hay for the soul", "the birds say hi", "i painted you. it's a brown square. it's you", "my spots are not an accident", "¿quieres ser mi musa?"] },
  { id: 'shadow', name: 'Shadow', age: 7, breed: 'Black Arabian', sex: 'Stallion', loc: 'Rotterdam, NL', height: '15.2 hands',
    photos: [P('shadow', 1, '🍂'), P('shadow', 2)],
    bio: "I don't do small talk. I do long gallops at midnight. If you see me, it's because I let you.",
    traits: ['Mysterious', 'Gorgeous', 'Brooding'], looking: 'Someone who understands silence.',
    stats: { 'Attractiveness': 'illegal in 4 countries', 'Words per day': '6' }, flags: ['Has never smiled on camera.'], chance: 0.3,
    lines: ["...", "the night is mine", "i don't text much. i gallop.", "you're different. i can smell it", "meet me at the edge of the paddock. midnight."] },
  { id: 'princess', name: 'Princess', age: 5, breed: 'Andalusian', sex: 'Mare', loc: 'Monaco', height: '15.2 hands (16 in heels)',
    photos: [P('princess', 1, 'mane appointment'), P('princess', 2), P('princess', 3, 'daddy bought me this halter')],
    bio: "If you can't handle me at my worst, you don't deserve my hay at its best. Only organic alfalfa. Don't ask twice.",
    traits: ['Diva', 'Expensive', 'Iconic'], looking: 'A stallion with a yacht (stable on yacht).',
    stats: { 'Mane budget': '€4,000/mo', 'Stable reputation': 'royalty' }, flags: ['Leaves everyone on read.', 'Has a groomer on retainer.'], chance: 0.2, ghost: 0.35,
    lines: ["ew", "k", "is that ur real saddle?", "my hay is imported", "you may continue", "💅"] },
  { id: 'bigtony', name: 'Big Tony', age: 14, breed: 'Miniature Horse', sex: 'Stallion', loc: 'Staten Island, NY', height: "2'4\"",
    photos: [P('bigtony', 1, 'me and my associate'), P('bigtony', 2, 'the office'), P('bigtony', 3, 'family property')],
    bio: "They call me Big Tony. Nobody knows why. Nobody asks twice. I got a guy for carrots.",
    traits: ['Connected', 'Loyal', 'Short-tempered'], looking: 'Loyalty. Respect. A step stool.',
    stats: { 'Height': "2'4\"", 'Favors owed': '37' }, flags: ['"Knows a guy" for everything.'], chance: 0.65,
    lines: ["you talkin to me?", "my cousin Sal can get us a table at the feed store", "fuggedaboutit", "nobody calls me small. nobody", "i got a guy for that", "capisce?"] },
  { id: 'diesel', name: 'Diesel', age: 12, breed: 'Clydesdale', sex: 'Stallion', loc: 'Glasgow, Scotland', height: '18 hands',
    photos: [P('diesel', 1, '1 ton of love'), P('diesel', 2, 'work fit'), P('diesel', 3), P('diesel', 4, 'me and my brother Little Diesel')],
    bio: "One ton of pure love. I pull carts for fun. Could pull you too (in a cart). Yes the leg hair is natural. It's called feathers, look it up.",
    traits: ['Gentle giant', 'Strong', 'Hairy'], looking: 'Someone who can handle my feathers.',
    stats: { 'Pulls': '8,000 lbs', 'Hoof size': 'dinner plate' }, flags: ['Has sat on a car. By accident. Twice.'], chance: 0.6,
    lines: ["aye", "i could pull a bus. want to see", "sorry i sat on something again", "my feathers are freshly conditioned", "wee carrot for the big lad?"] },
  { id: 'neighington', name: 'Sir Neighington III', age: 17, breed: 'Thoroughbred (Old Money)', sex: 'Stallion', loc: 'Kensington, London', height: '17 hands',
    photos: [P('neighington', 1, 'first place, obviously'), P('neighington', 2, 'dressage, darling'), P('neighington', 3, 'charity gala')],
    bio: "Third Earl of Upper Paddock. Monocle-adjacent. My great-great-grandsire lost to Seabiscuit and we do not speak of it.",
    traits: ['Posh', 'Rich', 'Polo'], looking: 'A mare of suitable lineage.',
    stats: { 'Net worth': '4 estates', 'Ribbons': '212' }, flags: ['Refers to other horses as "commoners".'], chance: 0.35,
    lines: ["how frightfully modern", "one's butler will reply shortly", "i summer in the Cotswolds", "do you play polo? pity", "splendid. simply splendid."] },
  { id: 'kevin', name: 'Kevin', age: 10, breed: 'Shetland Pony', sex: 'Gelding', loc: 'Leeds, UK', height: "6'2 (in pony years)",
    photos: [P('kevin', 1, 'me hearing a good pun'), P('kevin', 2, 'black and white = deep')],
    bio: "I will make you laugh, or at least make a noise at you. Why did the horse cross the road? To prove it was stable.",
    traits: ['Funny', 'Loud', 'Punny'], looking: 'An audience.',
    stats: { 'Puns per hour': '44', 'Laughs received': '3' }, flags: ['Laughs at his own jokes first.'], chance: 0.7,
    lines: ["what do u call a horse that lives next door? a neigh-bour 😂", "i'm not horsing around i'm serious", "whinny u free?", "hay is for horses. and so am i", "that's the mane event baby"] },
  { id: 'chad', name: 'Chad', age: 6, breed: 'Quarter Horse', sex: 'Stallion', loc: 'Miami, FL', height: '16 hands of muscle',
    photos: [P('chad', 1, 'no face pics. ask'), P('chad', 2, 'leg day (every day)'), P('chad', 3, 'home gym')],
    bio: "Deadlift 2 tons. Creatine in my oats. If you don't lift don't swipe. Face reveal at 10 likes 💪",
    traits: ['Gym', 'Protein', 'Gym again'], looking: 'A gym partner. Leg day only.',
    stats: { 'Max squat': '2 tons', 'Protein oats': '9 buckets/day' }, flags: ['No face pics.', 'Calls every workout "leg day".'], chance: 0.55,
    lines: ["bro", "did u lift today", "gains before mares. jk. unless", "i'm on my 4th bucket of protein oats", "let's get swole together 💪", "rest day is a myth"] },
  { id: 'juan', name: 'Juan', age: 8, breed: 'Peruvian Paso', sex: 'Stallion', loc: 'Lima, Peru', height: '15 hands',
    photos: [P('juan', 1, 'hola'), P('juan', 2, 'me and my mamá (owner)'), P('juan', 3, 'snacking')],
    bio: 'I walk with the smoothest gait in the world. Paso Fino means "fine step" and baby, I am fine. Salsa? I invented it.',
    traits: ['Romantic', 'Smooth', 'Dancer'], looking: 'Una pareja para bailar.',
    stats: { 'Smoothness': '11/10', 'Serenades sent': '800+' }, flags: ['Serenades at 3am.'], chance: 0.65,
    lines: ["hola hermosa 🌹", "you make my hooves weak", "let me serenade you: neighhhh 🎶", "mi corazón es tuyo (and my hay)", "i am smooth like my gait"] },
  { id: 'lightning', name: 'Lightning', age: 4, breed: 'Thoroughbred Racehorse', sex: 'Stallion', loc: 'Louisville, KY', height: '16.1 hands',
    photos: [P('lightning', 1), P('lightning', 2, 'at work')],
    bio: 'Fast in every way. EVERY way. Retired at 4 because I kept winning and it got awkward.',
    traits: ['Fast', 'Impatient', 'Winner'], looking: 'SOMEONE FAST. NOW. NO TIME.',
    stats: { 'Top speed': '70 km/h', 'Races won': '19' }, flags: ['Finishes everything too early.'], chance: 0.55, fast: true,
    lines: ["HEY", "WHAT'S UP", "SORRY TOO SLOW", "OK BYE", "JK IM BACK", "RACE ME", "U THERE??"] },
  { id: 'concrete', name: 'Concrete', age: 14, breed: 'Steel & Concrete', sex: 'Stallion', loc: 'M8 Motorway, Scotland', height: '30 metres',
    photos: [P('concrete', 1, 'my spot'), P('concrete', 2, 'me and my twin')],
    bio: "Great listener. Never leaves. Some say I'm emotionally unavailable. I say I'm load-bearing.",
    traits: ['Stable', 'Silent', 'Very stable'], looking: 'Someone who stays.',
    stats: { 'Carrots eaten': '0', 'Moves per year': '0' }, flags: ['Has not moved since 2008.'], chance: 0.9, ghost: 0.8,
    lines: [".", "...", "i am still here", "i will always be here", "a car went by"] },
  { id: 'ziggy', name: 'Ziggy', age: 7, breed: 'Horse (Very Normal)', sex: 'Stallion', loc: 'Serengeti, Tanzania', height: 'horse-sized',
    photos: [P('ziggy', 1, 'totally normal horse pic')],
    bio: "Before you ask: no. It's a pattern. Appaloosas have spots, I have stripes. Drop it.",
    traits: ['Horse', 'Normal horse', 'Horse'], looking: 'Someone who does NOT ask about the stripes.',
    stats: { 'Stripes': 'no comment', 'Lions evaded': '41' }, flags: ['Gets defensive about stripes.'], chance: 0.6,
    kw: { 'zebra|stripe': ["I AM NOT A ZEBRA", "it's a PATTERN", "blocked. jk. but don't"] },
    lines: ["just a regular horse here", "neigh (normal horse noise)", "what stripes", "ever been chased by a lion? no reason"] },
  { id: 'gerald', name: 'Gerald', age: 29, breed: 'Grey Pony', sex: 'Gelding', loc: 'Bournemouth, UK', height: '13 hands (used to be 14)',
    photos: [P('gerald', 1, 'recent pic (2024)'), P('gerald', 2), P('gerald', 3, 'summer 96')],
    bio: "Just turned 29 (again). Into TikTok, fidget spinners and other modern things young horses like. Lol.",
    traits: ['Young', 'Very young', 'Hip'], looking: 'A young mare. Like me. Young.',
    stats: { 'Actual age': '41', 'Knees': '2 (bad)' }, flags: ['That B&W photo is from 1904.'], chance: 0.9, slow: true,
    kw: { 'age|old|young|year': ["29. i am 29. why does everyone ask", "age is just a number. mine is 29", "i'm very young. Lol"] },
    lines: ["Hello. Lol. - Gerald", "How do I send a picture on here", "Lol means lots of love right", "The young horses say 'slay'. Slay. - Gerald", "Sorry was having a nap. Not because I'm old"] },
  { id: 'raven', name: 'Raven', age: 5, breed: 'Exmoor Pony', sex: 'Mare', loc: 'Manchester, UK', height: '12.2 hands',
    photos: [P('raven', 1, 'dont'), P('raven', 2, 'fringe day'), P('raven', 3, 'me at the concert')],
    bio: "My mane covers one eye because the world doesn't deserve to see both. Carrots are just orange sadness. 🖤",
    traits: ['Emo', 'Deep', 'Screamo'], looking: 'Someone who gets it (you won\'t)',
    stats: { 'Sadness': '100%', 'Black eyeliner': 'natural' }, flags: ['Screams at sunsets.'], chance: 0.5, lower: true,
    lines: ["whatever", "nobody understands my mane", "i'm not sad. i'm just a horse in the dark", "hay tastes like regret", "🖤", "it's not a phase mom"] },
  { id: 'skylar', name: 'Skylar', age: 6, breed: 'Haflinger', sex: 'Mare', loc: 'Los Angeles, CA', height: '14.2 hands',
    photos: [P('skylar', 1, 'wind machine? never heard of her'), P('skylar', 2, 'no filter'), P('skylar', 3, 'sunset collab 💕')],
    bio: 'Mane care routine in bio ✨ Collabs: DM. Code NEIGH10 for 10% off hoof oil. Living my best pasture life 🌅',
    traits: ['Influencer', 'Aesthetic', 'Golden hour'], looking: 'A boyfriend who takes good photos.',
    stats: { 'Followers': '48.2K', 'Selfies/day': '60' }, flags: ['Makes every date "content".'], chance: 0.45,
    lines: ["omg hiii ✨", "can u take my pic rn", "use code NEIGH10 💕", "the lighting in this paddock is so bad", "manifesting hay 🌾✨", "wait let me post this"] },
  { id: 'bjorn', name: 'Björn', age: 9, breed: 'Icelandic Horse', sex: 'Stallion', loc: 'Reykjavík, Iceland', height: '13.3 hands',
    photos: [P('bjorn', 1, 'summer (it was -4)'), P('bjorn', 2, 'winter coat era')],
    bio: 'I have five gaits. You have maybe two. Let that sink in. Pony-sized, Viking-souled.',
    traits: ['Tough', 'Fluffy', 'Viking'], looking: 'Someone who can tölt.',
    stats: { 'Gaits': '5', 'Coldest night': '-31°C' }, flags: ['Will tell you he is NOT a pony.'], chance: 0.55,
    kw: { 'pony': ["I AM NOT A PONY", "Icelandic HORSE. we have a whole law about it"] },
    lines: ["já", "have you tried the tölt? life changing", "it is -12 here, very nice", "my ancestors crossed oceans on longships", "fluffiest horse alive btw"] },
  { id: 'chardonnay', name: 'Chardonnay', age: 13, breed: 'Hanoverian', sex: 'Mare', loc: 'Napa Valley, CA', height: '16 hands',
    photos: [P('chardonnay', 1, 'mom mode'), P('chardonnay', 2, 'girls night 🍷'), P('chardonnay', 3, 'my son Brayden. he is my world')],
    bio: "Single mom. Wine mom. Hay mom. Brayden comes first. Live, Laugh, Lunge. 🍷",
    traits: ['Mom', 'Wine', 'Fun'], looking: 'A stepdad for Brayden.',
    stats: { 'Wine bottles': 'classified', 'Book club': 'every Thursday' }, flags: ['Brayden will be at the first date.'], chance: 0.6,
    lines: ["it's 5pm somewhere 🍷", "sorry brayden is being a menace", "girls night tonight!!", "live laugh lunge", "do u like kids? brayden is 1 and very fast"] },
  { id: 'officer', name: 'Officer Clip-Clop', age: 11, breed: 'Irish Draught (Mounted Police)', sex: 'Gelding', loc: 'New York, NY', height: '17 hands',
    photos: [P('officer', 1, 'on duty')],
    bio: "Here to protect and serve (carrots). Not wearing a wire, relax. Yes I have handcuffs. No they don't fit hooves.",
    traits: ['Brave', 'Rule-follower', 'Snitch'], looking: 'A law-abiding citizen.',
    stats: { 'Arrests': '0', 'Pats received': '1.3M' }, flags: ['Will read you your rights on the first date.'], chance: 0.5,
    lines: ["license and registration", "you have the right to remain cute", "i'll let you off with a warning 😉", "is that jaywalking??", "10-4"] },
  { id: 'todd', name: 'Todd', age: 8, breed: 'Lusitano', sex: 'Gelding', loc: 'Portland, OR', height: '15.3 hands',
    photos: [P('todd', 1, 'me and my ex Brenda (for context)'), P('todd', 2, 'me after')],
    bio: "Recently single. Not over it. Here's a picture of us, for context. Anyway how are you. Brenda liked apples.",
    traits: ['Sensitive', 'Honest', 'Not over it'], looking: 'Closure. Also you.',
    stats: { 'Days since Brenda': '3', 'Sad neighs': '600' }, flags: ['Every story ends with Brenda.'], chance: 0.8,
    lines: ["brenda used to say that", "sorry. anyway", "do you think she misses me", "we used to share a trough 😭", "you remind me of her. is that weird"] },
  { id: 'carl', name: 'Crypto Carl', age: 7, breed: 'Mustang', sex: 'Stallion', loc: 'Anywhere (my trailer)', height: '15 hands',
    photos: [P('carl', 1, 'my office'), P('carl', 2, 'beach = office')],
    bio: 'Early investor in HayCoin. Trailer life. Digital nomad. I sell NFTs of my hoofprints. Not financial advice. WAGMI 🚀',
    traits: ['Visionary', 'Broke', 'Bullish'], looking: 'Seed investors.',
    stats: { 'HayCoin': '4.2M (worth $3)', 'Pitch decks': '11' }, flags: ['Will pitch you before the first date.'], chance: 0.7,
    lines: ["gm", "have u heard of HayCoin 🚀", "we're so early", "wagmi", "i'm basically the Elon of horses", "not financial advice but buy HayCoin"] },
  { id: 'patches', name: 'Patches', age: 6, breed: 'Paint Horse', sex: 'Gelding', loc: 'Austin, TX', height: '15.1 hands',
    photos: [P('patches', 1, 'waiting for u'), P('patches', 2, 'still waiting')],
    bio: "Looking for my soulmate and I think it's you. We should move into a stable together. Too fast? Sorry. Unless?",
    traits: ['Clingy', 'Devoted', 'Intense'], looking: 'Marriage. Tonight.',
    stats: { 'Texts per minute': '14', 'Wedding boards': '6' }, flags: ['Already named your kids.'], chance: 0.95,
    lines: ["hiii", "why aren't u answering", "i already told my mom about you", "our foals would be so cute", "i love you. too soon? sorry. i love you", "are you mad at me"] },
  { id: 'domino', name: 'Domino', age: 5, breed: 'Leopard Appaloosa', sex: 'Stallion', loc: 'Boise, ID', height: '15 hands',
    photos: [P('domino', 1, 'studio shoot'), P('domino', 2, 'blep'), P('domino', 3)],
    bio: 'Not a Dalmatian. Stop asking. 101 spots? More like 1,001. Firefighters keep trying to recruit me.',
    traits: ['Spotty', 'Playful', 'Tired of dog jokes'], looking: 'Someone who connects the dots.',
    stats: { 'Spots': '1,001', 'Dog jokes endured': '∞' }, flags: ['Has bitten a Dalmatian.'], chance: 0.6,
    kw: { 'dog|dalmatian|puppy': ["I AM A HORSE", "every. single. time."] },
    lines: ["connect my dots 😏", "i am NOT a dog", "fun fact i have a spot shaped like texas", "woof. jk. neigh"] },
  { id: 'cheryl', name: 'Cheryl', age: 15, breed: 'Pony (Suburban)', sex: 'Mare', loc: 'Suburbs', height: '14 hands',
    photos: [P('cheryl', 1, 'when the hay is late'), P('cheryl', 2, 'inspecting the fence')],
    bio: "I'd like to speak to the stable manager. Hay was 4 minutes late. I've left a 1-star review on every farm in the county.",
    traits: ['Assertive', 'Organised', 'Litigious'], looking: 'Someone who respects standards.',
    stats: { 'Complaints filed': '2,114', 'Managers spoken to': '88' }, flags: ['Has had a farrier fired.'], chance: 0.5,
    lines: ["this app is terrible", "who is your manager", "i will be leaving a review", "excuse me??", "the hay here is UNACCEPTABLE"] },
  { id: 'brian', name: 'Brian', age: 12, breed: 'Shire / Draft Cross', sex: 'Gelding', loc: 'Doncaster, UK', height: '17.2 hands',
    photos: [P('brian', 1, 'me and the lads after the pub'), P('brian', 2, 'my smize')],
    bio: "Five pints of water in and I'm anyone's. Lads' holiday every summer (same field). Banter is my love language.",
    traits: ['Banter', 'Lad', 'Loud'], looking: 'A laugh 🍺',
    stats: { 'Pints (water)': '5 a night', 'Lads': '1 (asleep)' }, flags: ['Friend in photo 1 is asleep. Or worse.'], chance: 0.7,
    lines: ["oi oi", "absolute scenes", "the lads are asleep again", "mate", "fancy a trough?"] },
  { id: 'casper', name: 'Casper', age: 6, breed: 'Cremello', sex: 'Stallion', loc: 'Salem, MA', height: '15.2 hands',
    photos: [P('casper', 1, 'i knew you would swipe'), P('casper', 2, 'third eye')],
    bio: 'Psychic. I see things. I see your future. It is mostly hay. My blue eyes have seen 4 dimensions.',
    traits: ['Psychic', 'Spooky', 'Calm'], looking: 'You. I foresaw this.',
    stats: { 'Predictions correct': '100%', 'Dimensions': '4' }, flags: ['Answers before you ask.'], chance: 0.7,
    lines: ['i knew you would say "{msg}"', "i see a carrot in your future", "your aura is beige", "the spirits say you're a 7", "don't go outside on tuesday"] },
  { id: 'sergei', name: 'Sergei', age: 9, breed: "Przewalski's Horse", sex: 'Stallion', loc: 'Mongolian Steppe', height: '13 hands',
    photos: [P('sergei', 1, 'wild and free')],
    bio: 'LAST TRULY WILD HORSE. PALEO DIET. NEVER BEEN RIDDEN. I WILL BRING THIS UP ON THE FIRST DATE.',
    traits: ['WILD', 'PALEO', 'UNTAMED'], looking: 'A MARE WHO CAN SURVIVE WINTER',
    stats: { 'Times ridden': '0', 'Ancestors': '160,000 years' }, flags: ['Only speaks in caps.'], chance: 0.5, caps: true,
    lines: ["I AM WILD", "MY ANCESTORS SAW MAMMOTHS", "SADDLES ARE A LIE", "I EAT GRASS RAW. LIKE A MAN", "WINTER IS NOTHING TO ME"] },
  { id: 'gordon', name: 'Gordon', age: 10, breed: 'Quarter Horse', sex: 'Stallion', loc: 'Chicago, IL', height: '15.3 hands',
    photos: [P('gordon', 1, 'tasting menu'), P('gordon', 2, 'kitchen')],
    bio: "Foodie. Hay critic. I have strong opinions about timothy vs. alfalfa and I will share them. This hay is RAW.",
    traits: ['Foodie', 'Critic', 'Angry'], looking: 'Someone with a refined palate.',
    stats: { 'Michelin hay': '3 stars', 'Buckets kicked': '40' }, flags: ['Sent back a salt lick.'], chance: 0.5,
    lines: ["this hay is RAW", "what are you, an idiot sandwich", "timothy hay is overrated. there i said it", "come dine at my trough", "delicious. finally."] },
  { id: 'pickles', name: 'Pickles', age: 7, breed: 'Grade Horse', sex: 'Mare', loc: 'Portland, ME', height: '15 hands',
    photos: [P('pickles', 1, 'blep'), P('pickles', 2), P('pickles', 3, 'also blep'), P('pickles', 4, 'maximum blep')],
    bio: 'I lick things. Walls. Fences. Salt blocks. Possibly you. My tongue has its own fan club.',
    traits: ['Licky', 'Friendly', 'Unhinged'], looking: 'Something salty.',
    stats: { 'Surfaces licked': '9,440', 'Tongue length': 'too long' }, flags: ['Licked an electric fence (on purpose).'], chance: 0.7,
    lines: ["lick", "i licked the fence again", "u look salty. compliment", "👅", "is ur phone lickable"] },
  { id: 'maple', name: 'Maple', age: 6, breed: 'Canadian Horse', sex: 'Mare', loc: 'Quebec City, Canada', height: '15 hands',
    photos: [P('maple', 1, 'sorry for the snow'), P('maple', 2), P('maple', 3, 'blanket szn')],
    bio: 'Sorry in advance. Loves snow, maple syrup, and you (sorry, too soon?). Would apologise to a fence.',
    traits: ['Polite', 'Cosy', 'Sorry'], looking: 'Someone nice, eh.',
    stats: { 'Sorrys/day': '240', 'Syrup': 'on everything' }, flags: ['Apologised to a moose.'], chance: 0.65,
    lines: ["sorry!", "oh sorry, hi", "sorry for the late reply eh", "want some maple syrup? sorry", "sorry i said sorry"] },
  { id: 'walter', name: 'Walter', age: 9, breed: 'Chestnut Warmblood', sex: 'Gelding', loc: 'Bristol, UK', height: '16 hands',
    photos: [P('walter', 1, 'front camera'), P('walter', 2, 'caught me mid-laugh')],
    bio: 'Front camera enthusiast. Sorry for the angles, my neck is three feet long. Big laugh, bigger teeth.',
    traits: ['Selfie', 'Laugher', 'Friendly'], looking: 'Someone to hold the phone.',
    stats: { 'Selfies': '4,000', 'Nostril size': 'large' }, flags: ['Every photo is up his nose.'], chance: 0.65,
    lines: ["sent u a selfie", "HAHAHA", "my nose is not that big it's the lens", "say cheese (hay)"] },
  { id: 'rafael', name: 'Rafael', age: 7, breed: 'Hanoverian', sex: 'Stallion', loc: 'Milan, Italy', height: '17 hands',
    photos: [P('rafael', 1, 'campaign shoot'), P('rafael', 2, 'off duty')],
    bio: 'Model. Scorpio. My mane has its own agent. I only eat hay picked by moonlight.',
    traits: ['Model', 'Scorpio', 'Devastating'], looking: 'Someone who can keep up with Milan fashion week.',
    stats: { 'Attractiveness': '10/10', 'Mirrors owned': '14' }, flags: ['Kisses his own reflection.'], chance: 0.25,
    lines: ["ciao bella", "don't touch the mane", "my agent says i can't text after 9", "you're almost as pretty as me", "✨"] },
  { id: 'doug', name: 'Doug', age: 10, breed: 'Gypsy Cob', sex: 'Stallion', loc: 'Cork, Ireland', height: '14.2 hands',
    photos: [P('doug', 1, 'dad'), P('doug', 2, 'my boy Doug Jr.'), P('doug', 3, 'dad bod')],
    bio: "Single dad. Doug Jr. is my world. Grill master (hay). Dad jokes included at no extra cost.",
    traits: ['Dad', 'Reliable', 'Dad jokes'], looking: 'A partner in crime (and school runs).',
    stats: { 'Dad jokes': '∞', 'Grill': 'hay only' }, flags: ['Says "hi hungry, I\'m Doug".'], chance: 0.7,
    lines: ["hi hungry, i'm doug", "doug jr says hi", "what did the horse say when it fell? i've fallen and i can't giddy-up", "ask your mum if you can come over"] },
  { id: 'dolores', name: 'Dolores', age: 31, breed: 'Welsh Pony', sex: 'Mare', loc: 'Cardiff, Wales', height: '12 hands',
    photos: [P('dolores', 1, 'me')],
    bio: "Retired. Knit blankets (for myself). Looking for a companion to sit in silence with. Have you eaten? You look thin.",
    traits: ['Kind', 'Retired', 'Nosy'], looking: 'A nice young horse to feed.',
    stats: { 'Grandfoals': '22', 'Blankets knitted': '63' }, flags: ['Will force-feed you apples.'], chance: 0.85, slow: true,
    lines: ["hello dear", "are you eating enough", "wear a blanket it's cold", "my grandfoal set up this app", "here have an apple 🍎"] },
  { id: 'marina', name: 'Marina', age: 7, breed: 'Wild Assateague Pony', sex: 'Mare', loc: 'Assateague Island, MD', height: '13 hands',
    photos: [P('marina', 1, 'beach hair'), P('marina', 2, 'locals only')],
    bio: "Beach babe. Literally feral. Never paid rent. Tourists feed me chips and I have no regrets.",
    traits: ['Feral', 'Free', 'Salty'], looking: 'Someone with snacks.',
    stats: { 'Rent paid': '$0', 'Tourists robbed': '211' }, flags: ['Stole a sandwich from a toddler.'], chance: 0.55,
    lines: ["surf's up", "got chips?", "i live on a beach and pay nothing", "tourists are my ATM", "🌊🐴"] },
  { id: 'jingles', name: 'Jingles', age: 9, breed: 'Sleigh Horse', sex: 'Gelding', loc: 'Rovaniemi, Finland', height: '15.2 hands',
    photos: [P('jingles', 1, 'work uniform'), P('jingles', 2, 'my coworker')],
    bio: 'Seasonal worker. Swamped in December, free the rest of the year. Reindeer and I are NOT a thing.',
    traits: ['Festive', 'Hard-working', 'Jingly'], looking: 'A Christmas miracle.',
    stats: { 'Bells worn': '14', 'Reindeer beef': 'ongoing' }, flags: ['Cannot stop jingling.'], chance: 0.6,
    lines: ["jingle jingle", "the reindeer are so smug", "free till december 😉", "*jingles suggestively*", "ho ho neigh"] },
  // ───────── SPECIALS ─────────
  { id: 'bojack', special: 'star', early: true, name: 'BoJack Horseman', age: 52, breed: 'Horse (Actor)', sex: 'Stallion', loc: 'Hollywoo, CA', height: "6'3 (the loafers help)",
    photos: [{ src: 'img/horses/bojack-1.png', fit: 'contain', cap: 'headshot (recent-ish)' }, { slide: 'horsin', cap: "my show. you've seen it" }],
    bio: "Back in the 90s I was in a very famous TV show. Yes, THAT horse. Big house in the hills, bigger emotional baggage. Looking for someone to tell me I'm a good horse.",
    traits: ['Famous (formerly)', 'Self-aware (sometimes)', 'Sweater guy'], looking: "Someone to tell me I'm a good person. You can lie.",
    stats: { "Seasons of Horsin' Around": '9', 'Houseguests': '1 (Todd, 5 years)' }, flags: ['Lists his age as "early 40s".', 'There is a Todd on his couch. Permanently.', 'Will make the date about himself.'],
    chance: 0.5, rarity: 1, typing: 'is typing, deleting, and typing again',
    kw: { "horsin|show|tv|famous|sitcom": ["Horsin' Around. 1987 to 1996. nine seasons. look it up", "yes. THAT BoJack. you can say it", "the show holds up. mostly. don't watch season 6"],
      'todd': ["todd's still on my couch. it's been five years. he's thriving", "how do you know todd"],
      'good (person|horse|guy)': ["that's kind of the whole question isn't it", "i think so? ask me again after a drink. no. don't ask me after a drink"] },
    lines: ["you probably recognise me", "i'm not a bad horse. i'm a horse who sometimes does bad things. there's a difference. i think", "wanna come to a party at my house? everyone's coming. well. todd's here", "is this a date or are you a journalist", "diane would say i'm deflecting. i'm not deflecting. how's the weather where you are", "i matched with you because i was bored and sad. now i'm just sad. progress!", "the D fell off the sign in '08. we don't talk about it"] },
  { id: 'gary', special: 'verified', name: 'Gary', age: 12, breed: 'Horse', sex: 'Gelding', loc: 'Ohio', height: '15.3 hands',
    photos: [P('gary', 1, 'verified horse'), P('gary', 2, 'still verified')],
    bio: "Verified. That's it. That's the profile. Yes, I paid for the checkmark. No, I will not be taking questions.",
    traits: ['Verified', 'Authentic', 'Verified'], looking: 'Someone who respects the check.',
    stats: { 'Checkmarks': '1', 'Cost': '$8/month' }, flags: ['Mentions the checkmark every sentence.'], chance: 0.6, rarity: 0.85,
    lines: ["verified horse here ✓", "as a verified horse, i agree", "did you see my check", "✓"] },
  { id: 'lilhay', special: 'celebrity', name: 'Lil Hay', age: 8, breed: 'Mustang', sex: 'Stallion', loc: 'Atlanta, GA', height: '15.2 hands', followers: '1.2M',
    photos: [P('lilhay', 1, 'album cover'), P('lilhay', 2, 'tour life')],
    bio: 'Grammy-nominated (the Grammys don\'t know yet). New mixtape "Stable Genius" out now. 1.2M followers, 0 carrots.',
    traits: ['Famous', 'Rapper', 'Humble'], looking: 'A ride or neigh.',
    stats: { 'Followers': '1.2M', 'Monthly listeners': '3.4M' }, flags: ['Entourage of 12 donkeys.'], chance: 0.3, rarity: 0.85,
    lines: ["yo", "u know who i am right", "stream stable genius 🔥", "my manager will contact u", "hay in my pockets, neigh in my soul 🎤"] },
  { id: 'dah', special: 'imposter', name: 'Definitely A Horse', age: 34, breed: 'Horse (Regular)', sex: 'Stallion', loc: 'My apartment (stable)', height: "5'11 (on all four legs)",
    photos: [P('dah', 1, 'me eating grass (normal)'), P('dah', 2, 'me at my job (horse)'), P('dah', 3, 'me and my other legs'), P('dah', 4, 'family photo')],
    bio: "Hello fellow horse. I too enjoy eating the grass with my horse mouth. I have four legs, as is normal. Please do not look at my hands.",
    traits: ['Horse', 'Normal', 'Not a man'], looking: 'Horse things. Neigh.',
    stats: { 'Species': 'horse (100%)', 'Hands': 'none (0)' }, flags: ['Has hands.', 'Pays taxes.', 'Wears a watch.'], chance: 0.8, rarity: 0.9,
    lines: ["neigh. as horses do", "i love to walk on my 2 le— 4 legs", "brb my landlord is calling. i mean my farmer", "have you tried pizza? i mean hay", "i am typing this with my hooves"] },
  { id: 'mystery', special: 'mystery', name: 'Mystery Horse', age: '??', breed: '[REDACTED]', sex: '???', loc: '[CLASSIFIED]', height: '██ hands',
    photos: [P('mystery', 1), P('mystery', 2), P('mystery', 3)],
    bio: '████ ███ ██████ ████ ██ ███████. ███ ████ ██ █ █████ ███ ████████.',
    traits: ['███████', '████', '██████'], looking: '█████████',
    stats: { '██████': '███', 'Identity': 'unknown' }, flags: ['███████████████'], chance: 0.6, rarity: 0.8,
    reveals: [
      { name: 'Doris', img: 'img/horses/reveal-1.jpg', line: "She's been screaming since 2019. She's actually very nice." },
      { name: 'Two ponies’ butts', img: 'img/horses/reveal-2.jpg', line: "It was just two ponies' butts. It was always just two ponies' butts." },
      { name: 'Four guys in a costume', img: 'img/horses/reveal-3.jpg', line: 'It was a pantomime horse. Again. Why is it always a pantomime horse.' } ],
    lines: ["████", "you'll never know", "or will you", "█ ███ ████"] },
  { id: 'final', special: 'final', name: 'The Final Horse', age: '∞', breed: 'Primordial Stallion', sex: 'Stallion', loc: 'The Edge of the Map', height: 'Beyond measure',
    photos: [P('final', 1, 'I AM'), P('final', 2, 'the long winter')],
    bio: 'Before the first carrot, there was me. When the last stable door falls, I will still be standing. You have swiped through every lesser horse to reach this moment. Choose wisely, mortal.',
    traits: ['Eternal', 'Legendary', 'Final'], looking: 'THE ONE.',
    stats: { 'Carrots eaten': 'ALL OF THEM', 'Neigh rating': '★★★★★★★' }, flags: ['Is the end.'], chance: 0.5, rarity: 0.08,
    lines: ["IT IS WRITTEN.", "THE HAY SHALL FALL FROM THE SKY.", "YOU WERE ALWAYS MEANT TO FIND ME.", "SPEAK, MORTAL.", "THE PROPHECY IS FULFILLED."] },
];

// Non-photo "photos": styled slides rendered in place of an image.
const SLIDES = {
  horsin: `<small>ABC · FRIDAYS 8/7c</small><b>Horsin'<br>Around</b><em>1987 – 1996 · 9 seasons</em><span>"I didn't sign up for this!"</span>`,
};

const GENERIC = ["neigh", "u got carrots?", "send stable pics", "wyd later 🐴", "my owner isn't home", "lol", "hay 👋", "brb someone opened the feed bag", "sorry was rolling in mud", "whinny whinny 😂", "ngl ur kinda cute for a biped", "🥕?", "no thoughts just hay", "u up? (standing up. i sleep standing up)"];
const KW = [
  [/glue|dog food|lasagn|horse meat|burger/i, '__GLUE__'],
  [/carrot|🥕/i, ["did someone say CARROT", "🥕🥕🥕 marry me", "a carrot? for ME?", "i would do crimes for a carrot"]],
  [/^(hi|hey|hello|hay|sup|yo|hola|heyy+)\b/i, ["hay 👋", "neigh ;)", "sup", "hiiii", "hay there"]],
  [/pic|photo|selfie|stable/i, '__PIC__'],
  [/ride|saddle/i, ["whoa whoa buy me dinner first", "saddle? on the FIRST date??", "u have to earn the saddle"]],
  [/love|marry|wife|husband|boyfriend|girlfriend/i, ["already?? ok i'm in", "let's get a stable together", "love is a strong word. so is hay"]],
  [/date|meet|dinner|drink/i, ["wanna go stand in a field together", "i know a great trough downtown", "dinner at mine? it's hay. it's always hay"]],
  [/wyd|hru|how are you|what.*up/i, ["just standing", "eating. always eating", "staring at a wall for 3 hrs, u?", "rolling in mud, the usual"]],
  [/lol|haha|lmao|😂/i, ["lmao", "whinny whinny 😂", "ur funny for a biped"]],
  [/apple|sugar/i, ["APPLE?? 🍎", "sugar cubes are my weakness"]],
];
const COMPAT_CATS = ['Carrot compatibility', 'Stable chemistry', 'Gallop energy', 'Neigh frequency', 'Emotional availability', 'Mane-tenance level', 'Hay preference alignment', 'Trot synchronicity', 'Barn vibes', 'Hoof size compatibility', 'Fly-swat teamwork', 'Sugar cube tolerance'];
const PICKUP = ["hay there 👋", "u got carrots? 🥕", "send stable pics", "what's your favourite gait?", "come here often? 🌾", "i'd let you eat my garden"];
